ALTER TABLE mock_data_0 RENAME TO mock_data;

INSERT INTO mock_data
SELECT
	id + 1000,
	customer_first_name,
	customer_last_name,
	customer_age,
	customer_email,
	customer_country,
	customer_postal_code,
	customer_pet_type,
	customer_pet_name,
	customer_pet_breed,
	seller_first_name,
	seller_last_name,
	seller_email,
	seller_country,
	seller_postal_code,
	product_name,
	product_category,
	product_price,
	product_quantity,
	sale_date,
	sale_customer_id + 1000,
	sale_seller_id + 1000,
	sale_product_id + 1000,
	sale_quantity,
	sale_total_price,
	store_name,
	store_location,
	store_city,
	store_state,
	store_country,
	store_phone,
	store_email,
	pet_category,
	product_weight,
	product_color,
	product_size,
	product_brand,
	product_material,
	product_description,
	product_rating,
	product_reviews,
	product_release_date,
	product_expiry_date,
	supplier_name,
	supplier_contact,
	supplier_email,
	supplier_phone,
	supplier_address,
	supplier_city,
	supplier_country
FROM mock_data_1;

INSERT INTO mock_data
SELECT
	id + 2000,
	customer_first_name,
	customer_last_name,
	customer_age,
	customer_email,
	customer_country,
	customer_postal_code,
	customer_pet_type,
	customer_pet_name,
	customer_pet_breed,
	seller_first_name,
	seller_last_name,
	seller_email,
	seller_country,
	seller_postal_code,
	product_name,
	product_category,
	product_price,
	product_quantity,
	sale_date,
	sale_customer_id + 2000,
	sale_seller_id + 2000,
	sale_product_id + 2000,
	sale_quantity,
	sale_total_price,
	store_name,
	store_location,
	store_city,
	store_state,
	store_country,
	store_phone,
	store_email,
	pet_category,
	product_weight,
	product_color,
	product_size,
	product_brand,
	product_material,
	product_description,
	product_rating,
	product_reviews,
	product_release_date,
	product_expiry_date,
	supplier_name,
	supplier_contact,
	supplier_email,
	supplier_phone,
	supplier_address,
	supplier_city,
	supplier_country
FROM mock_data_2;

INSERT INTO mock_data
SELECT
	id + 3000,
	customer_first_name,
	customer_last_name,
	customer_age,
	customer_email,
	customer_country,
	customer_postal_code,
	customer_pet_type,
	customer_pet_name,
	customer_pet_breed,
	seller_first_name,
	seller_last_name,
	seller_email,
	seller_country,
	seller_postal_code,
	product_name,
	product_category,
	product_price,
	product_quantity,
	sale_date,
	sale_customer_id + 3000,
	sale_seller_id + 3000,
	sale_product_id + 3000,
	sale_quantity,
	sale_total_price,
	store_name,
	store_location,
	store_city,
	store_state,
	store_country,
	store_phone,
	store_email,
	pet_category,
	product_weight,
	product_color,
	product_size,
	product_brand,
	product_material,
	product_description,
	product_rating,
	product_reviews,
	product_release_date,
	product_expiry_date,
	supplier_name,
	supplier_contact,
	supplier_email,
	supplier_phone,
	supplier_address,
	supplier_city,
	supplier_country
FROM mock_data_3;

INSERT INTO mock_data
SELECT
	id + 4000,
	customer_first_name,
	customer_last_name,
	customer_age,
	customer_email,
	customer_country,
	customer_postal_code,
	customer_pet_type,
	customer_pet_name,
	customer_pet_breed,
	seller_first_name,
	seller_last_name,
	seller_email,
	seller_country,
	seller_postal_code,
	product_name,
	product_category,
	product_price,
	product_quantity,
	sale_date,
	sale_customer_id + 4000,
	sale_seller_id + 4000,
	sale_product_id + 4000,
	sale_quantity,
	sale_total_price,
	store_name,
	store_location,
	store_city,
	store_state,
	store_country,
	store_phone,
	store_email,
	pet_category,
	product_weight,
	product_color,
	product_size,
	product_brand,
	product_material,
	product_description,
	product_rating,
	product_reviews,
	product_release_date,
	product_expiry_date,
	supplier_name,
	supplier_contact,
	supplier_email,
	supplier_phone,
	supplier_address,
	supplier_city,
	supplier_country
FROM mock_data_4;

INSERT INTO mock_data
SELECT
	id + 5000,
	customer_first_name,
	customer_last_name,
	customer_age,
	customer_email,
	customer_country,
	customer_postal_code,
	customer_pet_type,
	customer_pet_name,
	customer_pet_breed,
	seller_first_name,
	seller_last_name,
	seller_email,
	seller_country,
	seller_postal_code,
	product_name,
	product_category,
	product_price,
	product_quantity,
	sale_date,
	sale_customer_id + 5000,
	sale_seller_id + 5000,
	sale_product_id + 5000,
	sale_quantity,
	sale_total_price,
	store_name,
	store_location,
	store_city,
	store_state,
	store_country,
	store_phone,
	store_email,
	pet_category,
	product_weight,
	product_color,
	product_size,
	product_brand,
	product_material,
	product_description,
	product_rating,
	product_reviews,
	product_release_date,
	product_expiry_date,
	supplier_name,
	supplier_contact,
	supplier_email,
	supplier_phone,
	supplier_address,
	supplier_city,
	supplier_country
FROM mock_data_5;

INSERT INTO mock_data
SELECT
	id + 6000,
	customer_first_name,
	customer_last_name,
	customer_age,
	customer_email,
	customer_country,
	customer_postal_code,
	customer_pet_type,
	customer_pet_name,
	customer_pet_breed,
	seller_first_name,
	seller_last_name,
	seller_email,
	seller_country,
	seller_postal_code,
	product_name,
	product_category,
	product_price,
	product_quantity,
	sale_date,
	sale_customer_id + 6000,
	sale_seller_id + 6000,
	sale_product_id + 6000,
	sale_quantity,
	sale_total_price,
	store_name,
	store_location,
	store_city,
	store_state,
	store_country,
	store_phone,
	store_email,
	pet_category,
	product_weight,
	product_color,
	product_size,
	product_brand,
	product_material,
	product_description,
	product_rating,
	product_reviews,
	product_release_date,
	product_expiry_date,
	supplier_name,
	supplier_contact,
	supplier_email,
	supplier_phone,
	supplier_address,
	supplier_city,
	supplier_country
FROM mock_data_6;

INSERT INTO mock_data
SELECT
	id + 7000,
	customer_first_name,
	customer_last_name,
	customer_age,
	customer_email,
	customer_country,
	customer_postal_code,
	customer_pet_type,
	customer_pet_name,
	customer_pet_breed,
	seller_first_name,
	seller_last_name,
	seller_email,
	seller_country,
	seller_postal_code,
	product_name,
	product_category,
	product_price,
	product_quantity,
	sale_date,
	sale_customer_id + 7000,
	sale_seller_id + 7000,
	sale_product_id + 7000,
	sale_quantity,
	sale_total_price,
	store_name,
	store_location,
	store_city,
	store_state,
	store_country,
	store_phone,
	store_email,
	pet_category,
	product_weight,
	product_color,
	product_size,
	product_brand,
	product_material,
	product_description,
	product_rating,
	product_reviews,
	product_release_date,
	product_expiry_date,
	supplier_name,
	supplier_contact,
	supplier_email,
	supplier_phone,
	supplier_address,
	supplier_city,
	supplier_country
FROM mock_data_7;

INSERT INTO mock_data
SELECT
	id + 8000,
	customer_first_name,
	customer_last_name,
	customer_age,
	customer_email,
	customer_country,
	customer_postal_code,
	customer_pet_type,
	customer_pet_name,
	customer_pet_breed,
	seller_first_name,
	seller_last_name,
	seller_email,
	seller_country,
	seller_postal_code,
	product_name,
	product_category,
	product_price,
	product_quantity,
	sale_date,
	sale_customer_id + 8000,
	sale_seller_id + 8000,
	sale_product_id + 8000,
	sale_quantity,
	sale_total_price,
	store_name,
	store_location,
	store_city,
	store_state,
	store_country,
	store_phone,
	store_email,
	pet_category,
	product_weight,
	product_color,
	product_size,
	product_brand,
	product_material,
	product_description,
	product_rating,
	product_reviews,
	product_release_date,
	product_expiry_date,
	supplier_name,
	supplier_contact,
	supplier_email,
	supplier_phone,
	supplier_address,
	supplier_city,
	supplier_country
FROM mock_data_8;

INSERT INTO mock_data
SELECT
	id + 9000,
	customer_first_name,
	customer_last_name,
	customer_age,
	customer_email,
	customer_country,
	customer_postal_code,
	customer_pet_type,
	customer_pet_name,
	customer_pet_breed,
	seller_first_name,
	seller_last_name,
	seller_email,
	seller_country,
	seller_postal_code,
	product_name,
	product_category,
	product_price,
	product_quantity,
	sale_date,
	sale_customer_id + 9000,
	sale_seller_id + 9000,
	sale_product_id + 9000,
	sale_quantity,
	sale_total_price,
	store_name,
	store_location,
	store_city,
	store_state,
	store_country,
	store_phone,
	store_email,
	pet_category,
	product_weight,
	product_color,
	product_size,
	product_brand,
	product_material,
	product_description,
	product_rating,
	product_reviews,
	product_release_date,
	product_expiry_date,
	supplier_name,
	supplier_contact,
	supplier_email,
	supplier_phone,
	supplier_address,
	supplier_city,
	supplier_country
FROM mock_data_9;
